### ISSUE TITLE
I made a new mistake.

### ISSUE THREAD

**Issue by juezhihe** [fakekey/orbwalk#2]
I successfully deployed the code and got it running.
Error prompt（Can't open driver）
Please help me solve it.
![17197210918497824724249716921215](https://github.com/fakekey/orbwalk/assets/169022739/44326fb4-80a7-453c-af0f-e28d79549a13)

**Comment by fakekey** [comment]
Yeah, we can't directly read memory because of the Vanguard, take a look at [this my repo](https://github.com/fakekey/Auto-Cleanse/releases). Download and extract it, it contain Chokevy64.sys which is driver that support read memory within kernel anti-cheat enabled. Just run Baker.exe and follow the instruction
